// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBTOGAA2xGXbaoGV1Pfx888m_VwElQeA7Y",
  authDomain: "test-70fc3.firebaseapp.com",
  projectId: "test-70fc3",
  storageBucket: "test-70fc3.firebasestorage.app",
  messagingSenderId: "1095656936616",
  appId: "1:1095656936616:web:854e9fdfa11ec475091e9d",
  measurementId: "G-J690J7SFN0"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBTOGAA2xGXbaoGV1Pfx888m_VwElQeA7Y",
  authDomain: "test-70fc3.firebaseapp.com",
  projectId: "test-70fc3",
  storageBucket: "test-70fc3.firebasestorage.app",
  messagingSenderId: "1095656936616",
  appId: "1:1095656936616:web:854e9fdfa11ec475091e9d",
  measurementId: "G-J690J7SFN0"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBTOGAA2xGXbaoGV1Pfx888m_VwElQeA7Y",
  authDomain: "test-70fc3.firebaseapp.com",
  projectId: "test-70fc3",
  storageBucket: "test-70fc3.firebasestorage.app",
  messagingSenderId: "1095656936616",
  appId: "1:1095656936616:web:854e9fdfa11ec475091e9d",
  measurementId: "G-J690J7SFN0"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBTOGAA2xGXbaoGV1Pfx888m_VwElQeA7Y",
  authDomain: "test-70fc3.firebaseapp.com",
  projectId: "test-70fc3",
  storageBucket: "test-70fc3.firebasestorage.app",
  messagingSenderId: "1095656936616",
  appId: "1:1095656936616:web:854e9fdfa11ec475091e9d",
  measurementId: "G-J690J7SFN0"
  );
}